site_url = "https://hello.onarchival.dev"
prebuild = ["npm ci"]

[editor_types.butt]
validate = []
editor_url = ""

[editor_types.butt2]
validate = ["magic"]
editor_url = ""

[editor_types.metabutt]
editor_url = ""

[[editor_types.metabutt.validate]]
path = "foo.bar.baz"
validate = "^[bB]"

[editor_types.custom_type]
validate = []
editor_url = "http://localhost:9090/editor.html"
