order = 40
name = "First Names"
body = """
# HELLO22
Here is some *content*"""

[[child]]
string_validated = "i didn't say the magic word"

[child.stuff.foo.bar]
baz = "Butt"

[[child]]
string_validated = "A SORT"

[[child]]
string_validated = "B SORT"

[[child]]
